# Generated by Django 3.2.16 on 2023-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
