# Generated by Django 3.2.16 on 2023-09-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
