# Generated by Django 3.2.16 on 2023-09-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conversationmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
