# Generated by Django 4.2.6 on 2023-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_confeedback_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ConFeedback',
        ),
    ]
